/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Code.Data;
import Code.HashTable2;
import Code.HashTable;
import Connection.koneksi;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class Penyetoran extends javax.swing.JFrame {
    
    //refrensi variabel dan objek
    Data swing2 = new HashTable(10);
    HashTable2 ht2 = new HashTable2(11);
    
    public DefaultTableModel model;
    private ResultSet hasil;
    /**
     * Creates new form Penyetoran
     */
    public Penyetoran() {
        initComponents();
        inisialisasi1();
        inisialisasi2();
        // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        
        //Data Penyetoran
        String[] judul = {"No ID","Nama Peternakan","Nama Pemilik","Tanggal Setor","Jenis Lebah","Jumlah Madu"};
        model = new DefaultTableModel(judul, 0);
        tabel_data.setModel(model);
        tabeldata();
        bt_riwayat.setVisible(false);
    }

    private void inisialisasi1(){
        txt_hbee.setText("HONEYBEE MALANG");
        txt_tanggal.setText("Jum'at, 16 Desember 2022");
        txt_ketpeternakan.setText("Nama Peternakan");
        txt_peternakan.setText("--------");
        txt_ketpemilik.setText("Nama Pemilik");
        txt_pemilik.setText("--------");
    }
    
    private void inisialisasi2(){
        txt_1.setText("Ruangan Sudah Terisi");
        txt_2.setText("--------");
        txt_3.setText("Ruangan Telah Kosong");
        txt_4.setText("--------");
        txt_5.setText("Ruangan Masih Terisi");
        txt_6.setText("--------");
    }
    
    private void inisialisasi3(){
        txt_10.setText("Ruang ke ");
        txt_11.setText("Ruang ke ");
    }
    
    public void tabeldata() {
        try {
            hasil = swing2.PrintData();
            while (hasil.next()) {
                swing2.setData(hasil.getInt("data"));
                swing2.setNama_peternakan(hasil.getString("nama_peternakan"));
                swing2.setNama_pemilik(hasil.getString("nama_pemilik"));
                swing2.setTanggal_setor(hasil.getString("tanggal_setor"));
                swing2.setJenis_lebah(hasil.getString("jenis_lebah"));
                swing2.setJumlah_madu(hasil.getString("jumlah_madu"));

                String[] data = {String.valueOf(swing2.getData()), swing2.getNama_peternakan(), swing2.getNama_pemilik(), swing2.getTanggal_setor(), swing2.getJenis_lebah(), swing2.getJumlah_madu()};
                model.addRow(data);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public void Reset() {
        txt_id1.setText("");
        txt_namapeternakan1.setText("");
        txt_namapemilik1.setText("");
        txt_tanggalsetor1.setText("");
        combo_jenislLebah1.setSelectedItem("");
        txt_jumlahmadu1.setText("");
    }
    
    public void Reset1() {
        txt_ruang.setText("");
        txt_anggota.setText("");
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_namapeternakan = new javax.swing.JTextField();
        bt_simpan = new javax.swing.JButton();
        txt_namapemilik = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_tanggalsetor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        combo_jenislebah = new javax.swing.JComboBox<>();
        txt_jumlahmadu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_namapeternakan1 = new javax.swing.JTextField();
        bt_simpan1 = new javax.swing.JButton();
        txt_namapemilik1 = new javax.swing.JTextField();
        txt_id1 = new javax.swing.JTextField();
        txt_tanggalsetor1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        combo_jenislLebah1 = new javax.swing.JComboBox<>();
        txt_jumlahmadu1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        bt_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_data = new javax.swing.JTable();
        bt_perbarui = new javax.swing.JButton();
        bt_riwayat = new javax.swing.JButton();
        bt_kembali = new javax.swing.JButton();
        txt_ruang = new javax.swing.JTextField();
        txt_anggota = new javax.swing.JTextField();
        txt_ruangcari = new javax.swing.JTextField();
        bt_proses = new javax.swing.JButton();
        bt_cari = new javax.swing.JButton();
        bt_selesai = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_hbee = new javax.swing.JLabel();
        txt_tanggal = new javax.swing.JLabel();
        txt_ketpeternakan = new javax.swing.JLabel();
        txt_peternakan = new javax.swing.JLabel();
        txt_ketpemilik = new javax.swing.JLabel();
        txt_pemilik = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_ruanghapus = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txt_1 = new javax.swing.JLabel();
        txt_2 = new javax.swing.JLabel();
        txt_3 = new javax.swing.JLabel();
        txt_4 = new javax.swing.JLabel();
        txt_5 = new javax.swing.JLabel();
        txt_6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txt_11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txt_10 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 32)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("PENYETORAN");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 102));
        jLabel14.setText("Jumlah Susu");

        txt_namapeternakan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        bt_simpan.setBackground(new java.awt.Color(0, 51, 102));
        bt_simpan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_simpan.setForeground(new java.awt.Color(255, 255, 255));
        bt_simpan.setText("SIMPAN");
        bt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanActionPerformed(evt);
            }
        });

        txt_namapemilik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_tanggalsetor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 102));
        jLabel16.setText("No. ID");

        combo_jenislebah.setEditable(true);
        combo_jenislebah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_jenislebah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Friesian Holstein", "Jersey", "Ayarshire", "Frieswal", "Hissar", "Gir" }));

        txt_jumlahmadu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Liter");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("Nama Peternakan");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 102));
        jLabel11.setText("Nama Pemilik");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 102));
        jLabel12.setText("Tanggal Setor");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 102));
        jLabel13.setText("Jenis Sapi");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 32)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("PENYETORAN");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 102));
        jLabel15.setText("Jumlah Madu");

        txt_namapeternakan1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        bt_simpan1.setBackground(new java.awt.Color(0, 51, 102));
        bt_simpan1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_simpan1.setForeground(new java.awt.Color(255, 255, 255));
        bt_simpan1.setText("SIMPAN");
        bt_simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpan1ActionPerformed(evt);
            }
        });

        txt_namapemilik1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_id1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_tanggalsetor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 102));
        jLabel17.setText("No. ID");

        combo_jenislLebah1.setEditable(true);
        combo_jenislLebah1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_jenislLebah1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apis Cerana", "Apis Mellifera", "Apis Dorsata", "Apis Nigrocincta", "Apis Florea" }));
        combo_jenislLebah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_jenislLebah1ActionPerformed(evt);
            }
        });

        txt_jumlahmadu1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("Gram");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 102));
        jLabel18.setText("Nama Peternakan");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 102));
        jLabel19.setText("Nama Pemilik");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 102));
        jLabel20.setText("Tanggal Setor");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 51, 102));
        jLabel21.setText("Jenis Lebah");

        bt_hapus.setBackground(new java.awt.Color(0, 51, 102));
        bt_hapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_hapus.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapus.setText("HAPUS");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        tabel_data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabel_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No. ID", "Nama Peternakan", "Nama Pemilik", "Tanggal Setor", "Jenis Lebah", "Jumlah Madu"
            }
        ));
        tabel_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_data);

        bt_perbarui.setBackground(new java.awt.Color(0, 51, 102));
        bt_perbarui.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_perbarui.setForeground(new java.awt.Color(255, 255, 255));
        bt_perbarui.setText("PERBARUI");
        bt_perbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_perbaruiActionPerformed(evt);
            }
        });

        bt_riwayat.setBackground(new java.awt.Color(0, 51, 102));
        bt_riwayat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_riwayat.setForeground(new java.awt.Color(255, 255, 255));
        bt_riwayat.setText("RIWAYAT");
        bt_riwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_riwayatActionPerformed(evt);
            }
        });

        bt_kembali.setBackground(new java.awt.Color(0, 51, 102));
        bt_kembali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_kembali.setForeground(new java.awt.Color(255, 255, 255));
        bt_kembali.setText("KEMBALI");
        bt_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_kembaliActionPerformed(evt);
            }
        });

        txt_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_anggotaActionPerformed(evt);
            }
        });

        txt_ruangcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ruangcariActionPerformed(evt);
            }
        });

        bt_proses.setBackground(new java.awt.Color(0, 51, 102));
        bt_proses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_proses.setForeground(new java.awt.Color(255, 255, 255));
        bt_proses.setText("PROSES");
        bt_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_prosesActionPerformed(evt);
            }
        });

        bt_cari.setBackground(new java.awt.Color(0, 51, 102));
        bt_cari.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_cari.setForeground(new java.awt.Color(255, 255, 255));
        bt_cari.setText("CARI");
        bt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cariActionPerformed(evt);
            }
        });

        bt_selesai.setBackground(new java.awt.Color(0, 51, 102));
        bt_selesai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_selesai.setForeground(new java.awt.Color(255, 255, 255));
        bt_selesai.setText("SELESAI");
        bt_selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_selesaiActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        txt_hbee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_hbee.setForeground(new java.awt.Color(255, 255, 255));
        txt_hbee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt_tanggal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        txt_tanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt_ketpeternakan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ketpeternakan.setForeground(new java.awt.Color(255, 255, 255));
        txt_ketpeternakan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt_peternakan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_peternakan.setForeground(new java.awt.Color(255, 255, 255));
        txt_peternakan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt_ketpemilik.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ketpemilik.setForeground(new java.awt.Color(255, 255, 255));
        txt_ketpemilik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_ketpemilik.setToolTipText("");

        txt_pemilik.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_pemilik.setForeground(new java.awt.Color(255, 255, 255));
        txt_pemilik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_hbee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_ketpeternakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_peternakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_ketpemilik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_pemilik, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_hbee, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ketpeternakan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_peternakan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ketpemilik, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pemilik, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("RUANG SETOR");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CEK RUANG");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("NAMA PETERNAKAN");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText(" TELAH SELESAI DARI RUANG  ");

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));

        txt_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_1.setForeground(new java.awt.Color(255, 255, 255));
        txt_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_2.setForeground(new java.awt.Color(255, 255, 255));
        txt_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_3.setForeground(new java.awt.Color(255, 255, 255));
        txt_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_4.setForeground(new java.awt.Color(255, 255, 255));
        txt_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt_5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_5.setForeground(new java.awt.Color(255, 255, 255));
        txt_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt_6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_6.setForeground(new java.awt.Color(255, 255, 255));
        txt_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_6, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 51, 102));
        jPanel6.setForeground(new java.awt.Color(0, 51, 102));

        txt_11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_11.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_11, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(0, 51, 102));
        jPanel7.setForeground(new java.awt.Color(0, 51, 102));

        txt_10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_10.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(571, 571, 571)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(bt_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(396, 396, 396)
                        .addComponent(bt_simpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_perbarui, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_riwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel15)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_namapeternakan1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_namapemilik1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tanggalsetor1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_jenislLebah1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_jumlahmadu1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(98, 98, 98)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2))
                    .addComponent(txt_ruang, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6))
                    .addComponent(txt_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_proses, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ruanghapus, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(bt_selesai, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ruangcari)
                            .addComponent(bt_cari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel17)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(txt_namapeternakan1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(txt_namapemilik1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(txt_tanggalsetor1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(combo_jenislLebah1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txt_jumlahmadu1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_simpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_perbarui, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_riwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(7, 7, 7)
                                .addComponent(txt_ruang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel6)
                                .addGap(7, 7, 7)
                                .addComponent(txt_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ruangcari, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(bt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(7, 7, 7)
                                .addComponent(txt_ruanghapus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(bt_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_proses, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_simpanActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        //TODO add your handling code here:
        //String hapus = txt_namapeternakan1.getText();
        try {
            String sql ="DELETE from penyetoran";
            java.sql.Connection conn=(Connection)koneksi.koneksiDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Pesanan Anda Telah Dihapus!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal DiHapus");
        }
        this.setVisible(false);
        new Penyetoran().setVisible(true);
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void tabel_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_dataMouseClicked
        // TODO add your handling code here:
        // menampilkan data kedalam form pengisian:
        int baris = tabel_data.getSelectedRow();
        if(baris > -1){
            String noid = tabel_data.getValueAt(baris, 0).toString();
            txt_id1.setText(noid);
            String namapeternakan = tabel_data.getValueAt(baris, 1).toString();
            txt_namapeternakan1.setText(namapeternakan);
            String namapemilik = tabel_data.getValueAt(baris,2).toString();
            txt_namapemilik1.setText(namapemilik);
            String tanggalsetor = tabel_data.getValueAt(baris, 3).toString();
            txt_tanggalsetor1.setText(tanggalsetor);
            String jenislebah = tabel_data.getValueAt(baris, 4).toString();
            combo_jenislLebah1.setSelectedItem(jenislebah);
            String jumlahmadu = tabel_data.getValueAt(baris,5).toString();
            txt_jumlahmadu1.setText(jumlahmadu);                    

            txt_hbee.setText("HONEYBEE MALANG");
            txt_tanggal.setText("Jum'at, 16 Desember 2022");
            txt_ketpeternakan.setText("Nama Peternakan");
            txt_peternakan.setText("  " + namapeternakan);
            txt_ketpemilik.setText("Nama Pemilik");
            txt_pemilik.setText("  " + namapemilik);
        }
    }//GEN-LAST:event_tabel_dataMouseClicked

    private void bt_perbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_perbaruiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Penyetoran().setVisible(true);
    }//GEN-LAST:event_bt_perbaruiActionPerformed

    private void bt_riwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_riwayatActionPerformed
        // TODO add your handling code here:
        try {
            int noid = Integer.parseInt(txt_id1.getText());
            String nama_peternakan = txt_namapeternakan1.getText();
            String nama_pemilik = txt_namapemilik1.getText();
            String tanggal_setor = txt_tanggalsetor1.getText();
            String jenis_lebah = combo_jenislLebah1.getSelectedItem().toString();
            String jumlah_madu= txt_jumlahmadu1.getText();
            
            swing2.insert(noid, nama_peternakan, nama_pemilik, tanggal_setor, jenis_lebah, jumlah_madu);
            swing2.displayTable();
            Reset();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_bt_riwayatActionPerformed

    private void bt_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_kembaliActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_bt_kembaliActionPerformed

    private void bt_simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpan1ActionPerformed
        // TODO add your handling code here:
        try {
            int noid = Integer.parseInt(txt_id1.getText());
            String nama_peternakan = txt_namapeternakan1.getText();
            String nama_pemilik = txt_namapemilik1.getText();
            String tanggal_setor = txt_tanggalsetor1.getText();
            String jenis_lebah = combo_jenislLebah1.getSelectedItem().toString();
            String jumlah_madu = txt_jumlahmadu1.getText();
            
            swing2.insertDB(noid, nama_peternakan, nama_pemilik, tanggal_setor, jenis_lebah, jumlah_madu);

            Reset();
        } catch (Exception e) {
            System.out.println(e);
        }
        this.setVisible(false);
        new Penyetoran().setVisible(true);
    }//GEN-LAST:event_bt_simpan1ActionPerformed

    private void txt_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_anggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_anggotaActionPerformed

    private void bt_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_prosesActionPerformed
        // TODO add your handling code here:
        try {
            int data = Integer.parseInt(txt_ruang.getText());
            String anggota = txt_anggota.getText();
            
            ht2.insert2(data, anggota);
            ht2.displayTable2();
            txt_1.setText("Ruangan Sudah Terisi");
            txt_2.setText("  " + data);
            Reset1();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_bt_prosesActionPerformed

    private void bt_selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_selesaiActionPerformed
        // TODO add your handling code here:
        int key = Integer.parseInt(txt_ruanghapus.getText());
        if (ht2.delete2(key)!=null) {
            System.out.println("Ruang ke - " + key + " telah selesai dan kosong");
            txt_3.setText("Ruangan Telah Kosong");
            txt_4.setText("  " + key);
            txt_ruanghapus.setText("");
        }
        else {
            System.out.println("Ruang ke - " + key + " kosong");
            txt_10.setText("Ruang ke - " + key + " kosong");
            txt_ruanghapus.setText("");
        }
    }//GEN-LAST:event_bt_selesaiActionPerformed

    private void bt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cariActionPerformed
        // TODO add your handling code here:
        int key = Integer.parseInt(txt_ruangcari.getText());
        if (ht2.find2(key)!=null) {
            System.out.println("Ruang ke - " + key + " masih terisi");
            txt_5.setText("Ruangan Masih Terisi");
            txt_6.setText("  " + key);
            txt_ruangcari.setText("");
        }
        else {
            System.out.println("Ruang ke - " + key + " kosong");
            txt_11.setText("Ruang ke - " + key + " kosong");
            txt_ruangcari.setText("");
        }
    }//GEN-LAST:event_bt_cariActionPerformed

    private void txt_ruangcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ruangcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ruangcariActionPerformed

    private void combo_jenislLebah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_jenislLebah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_jenislLebah1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penyetoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penyetoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penyetoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penyetoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penyetoran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cari;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_kembali;
    private javax.swing.JButton bt_perbarui;
    private javax.swing.JButton bt_proses;
    private javax.swing.JButton bt_riwayat;
    private javax.swing.JButton bt_selesai;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JButton bt_simpan1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo_jenislLebah1;
    private javax.swing.JComboBox<String> combo_jenislebah;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_data;
    private javax.swing.JLabel txt_1;
    private javax.swing.JLabel txt_10;
    private javax.swing.JLabel txt_11;
    private javax.swing.JLabel txt_2;
    private javax.swing.JLabel txt_3;
    private javax.swing.JLabel txt_4;
    private javax.swing.JLabel txt_5;
    private javax.swing.JLabel txt_6;
    private javax.swing.JTextField txt_anggota;
    private javax.swing.JLabel txt_hbee;
    private javax.swing.JTextField txt_id;
    public javax.swing.JTextField txt_id1;
    private javax.swing.JTextField txt_jumlahmadu;
    private javax.swing.JTextField txt_jumlahmadu1;
    private javax.swing.JLabel txt_ketpemilik;
    private javax.swing.JLabel txt_ketpeternakan;
    private javax.swing.JTextField txt_namapemilik;
    private javax.swing.JTextField txt_namapemilik1;
    private javax.swing.JTextField txt_namapeternakan;
    private javax.swing.JTextField txt_namapeternakan1;
    private javax.swing.JLabel txt_pemilik;
    private javax.swing.JLabel txt_peternakan;
    private javax.swing.JTextField txt_ruang;
    private javax.swing.JTextField txt_ruangcari;
    private javax.swing.JTextField txt_ruanghapus;
    private javax.swing.JLabel txt_tanggal;
    private javax.swing.JTextField txt_tanggalsetor;
    private javax.swing.JTextField txt_tanggalsetor1;
    // End of variables declaration//GEN-END:variables
}
